#!/bin/bash
echo 'Please allow root permission'
eval 'sudo'
echo 'Updating repos'
eval 'sudo apt update'
echo 'Installing updates'
eval 'sudo apt upgrade -y'
echo 'Setting up coding enviroment'
eval 'sudo apt-get install php php-xml php-curl nodejs npm curl wget composer git -y'
eval 'wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb'
eval 'wget https://az764295.vo.msecnd.net/stable/d045a5eda657f4d7b676dedbfa7aab8207f8a075/code_1.72.2-1665614327_amd64.deb'
eval 'wget https://autoupdate.termius.com/linux/Termius.deb'
eval 'sudo apt install ./google-chrome-stable_current_amd64.deb -y'
eval 'sudo apt install ./code_1.72.2-1665614327_amd64.deb -y'
eval 'sudo apt install ./Termius.deb -y'
echo 'Git setup'
read -p "Enter your github username: " username
read -p "Enter your github email: " email
eval 'git config --global user.name "'$username'"'
eval 'git config --global user.email "'$email'"'
eval 'ssh-keygen -t rsa -C "'$email'"'
echo 'Your github ssh key is:'
eval 'cat ~/.ssh/id_rsa.pub'
echo 'Add you key to https://github.com/settings/keys and close your browser'
eval 'x-www-browser https://github.com/settings/keys'
eval 'ssh -T git@github.com'
echo 'Tailscale Setup'
eval 'curl -fsSL https://tailscale.com/install.sh | sh'
eval 'sudo snap install telegram-desktop'
echo 'Finalising packages'
eval 'sudo apt update'
eval 'sudo apt upgrade -y'
eval 'clear'
echo 'Enviroment setup done enjoy ;)'
