#!/bin/bash
echo 'Updating repos'
eval 'sudo apt update'
echo 'Installing updates'
eval 'sudo apt upgrade -y'
echo 'Setting up coding enviroment'
eval 'sudo apt-get install php php-xml nodejs npm curl wget composer -y'
eval 'wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb'
eval 'wget https://az764295.vo.msecnd.net/stable/d045a5eda657f4d7b676dedbfa7aab8207f8a075/code_1.72.2-1665614327_amd64.deb'
eval 'sudo apt install ./google-chrome-stable_current_amd64.deb -y'
eval 'sudo apt install ./code_1.72.2-1665614327_amd64.deb -y'
echo 'Finalising packages'
eval 'sudo apt update'
eval 'sudo apt upgrade -y'
echo 'Enviroment setup done'
